// GENERATED by scripts/parse-reference-numbers.mjs — do not edit.
//
// Every value here was PARSED from docs/research/live/live-run-findings.md at build time (demo-app.md leg
// d8). The line number each came from is carried with it so the page can point
// at the record rather than asking to be believed.
//
// Generated at build time from a file in this repository. No network involved.

export interface ReferenceNumber {
  readonly name: string;
  readonly value: string;
  readonly sourceLine: number;
}

export const REFERENCE_SOURCE = "docs/research/live/live-run-findings.md";

export const REFERENCE: Record<string, ReferenceNumber> = {
  coldStartNative: { name: "coldStartNative", value: "5.97 s", sourceLine: 130 },
  coldStartPeakRss: { name: "coldStartPeakRss", value: "31 MB", sourceLine: 130 },
  warmResync: { name: "warmResync", value: "0.03 s", sourceLine: 132 },
  clientMirrorOnDisk: { name: "clientMirrorOnDisk", value: "60 MB", sourceLine: 133 },
  events: { name: "events", value: "118,960", sourceLine: 69 },
  poolActiveBlocks: { name: "poolActiveBlocks", value: "28,383", sourceLine: 69 },
  mainnetEpochs: { name: "mainnetEpochs", value: "515", sourceLine: 69 },
  mainnetFeedBytes: { name: "mainnetFeedBytes", value: "16 MB", sourceLine: 69 },
  storageWrites: { name: "storageWrites", value: "139,131", sourceLine: 134 },
  storageDistinctSlots: { name: "storageDistinctSlots", value: "134,879", sourceLine: 134 },
  anonymitySet: { name: "anonymitySet", value: "31,077", sourceLine: 147 },
  sepoliaDiscovery: { name: "sepoliaDiscovery", value: "1.19 s", sourceLine: 207 },
  abRequests: { name: "abRequests", value: "609", sourceLine: 220 },
  abBytes: { name: "abBytes", value: "64,509", sourceLine: 220 },
  sepoliaNoteBlock: { name: "sepoliaNoteBlock", value: "14,339,115", sourceLine: 189 },
  sepoliaSpendBlock: { name: "sepoliaSpendBlock", value: "14,340,785", sourceLine: 250 },
};

/** Arithmetic over parsed values. NEVER shown in a live readout (§6.3). */
export const DERIVED: Record<string, { readonly value: string; readonly formula: string }> = {
  "mainnetRequests": {
    "value": "518",
    "formula": "1 genesis + 1 manifest + 515 epochs + 1 head"
  }
};
